#!/bin/bash
# This scripts starts and restarts, if necessary, the btu_meter.py program.
# Any arguments passed to this script are passed to the btu_meter program.
until /home/pi/pi-energy-sensors/btu_meter.py "$@"; do
    echo "Script 'btu_meter.py' crashed with exit code $?.  Respawning.." >&2
    sleep 2
done
