#!/bin/bash
# This scripts starts and restarts, if necessary, the pulse_counter_multi_ch.py program.
# Any arguments passed to this script are passed to the pulse_counter_1ch program.
sleep 30
until /home/pi/pi-energy-sensors/pulse_counter_multi_ch.py "$@"; do
    echo "Script 'pulse_counter_multi_ch.py' crashed with exit code $?.  Respawning.." >&2
    sleep 2
done
